name: Backend CI/CD

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build the Spring Boot application
    - name: Build Backend
      run: ./mvnw clean package -DskipTests

    # Deploy to AWS EC2
    - name: Deploy to AWS EC2
      env:
        HOST: be.eventsflow.online 
        USER: ubuntu        
        KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      run: |
        scp -o StrictHostKeyChecking=no -i "$KEY" target/*.jar $USER@$HOST:/home/$USER/eventFlowBackend.jar
        ssh -o StrictHostKeyChecking=no -i "$KEY" $USER@$HOST << EOF
          pkill -f eventFlowBackend.jar || true
          nohup java -jar /home/$USER/eventFlowBackend.jar > /home/$USER/eventFlowBackend.log 2>&1 &
        EOF
