name: Backend CI/CD

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Debug Maven Wrapper Permissions
    - name: Debug Maven Wrapper Permissions
      run: ls -l mvnw

    # Make Maven Wrapper Executable
    - name: Make Maven Wrapper Executable
      run: chmod +x mvnw

    # Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Build the Spring Boot application
    - name: Build Backend
      run: ./mvnw clean package -DskipTests

    # Deploy to AWS EC2
    - name: Deploy to AWS EC2
      env:
        HOST: ${{ secrets.HOST }}       # Host stored as GitHub Secret
        USER: ${{ secrets.USER }}       # User stored as GitHub Secret
        KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      run: |
        # Copy the JAR file to the EC2 instance
        scp -o StrictHostKeyChecking=no -i "$KEY" target/*.jar $USER@$HOST:/home/$USER/eventFlowBackend.jar
        
        # SSH into the instance and deploy the application
        ssh -o StrictHostKeyChecking=no -i "$KEY" $USER@$HOST << EOF
          # Kill any running instance of the application
          pkill -f eventFlowBackend.jar || true
          
          # Start the new application in the background
          nohup java -jar /home/$USER/eventFlowBackend.jar > /home/$USER/eventFlowBackend.log 2>&1 &
        EOF
